[profile.default]
solc_version = '0.8.16'
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
fs_permissions = [
    { access = "read", path = "./lib/pwn_protocol/deployments/v1.4.json"},
    { access = "read", path = "./lib/pwn_protocol/deployments/external/external.json"}
]


[rpc_endpoints]
# Mainnets
mainnet = "${ETHEREUM_URL}"
world = "${WORLDCHAIN_URL}"
