[profile.default]
solc_version = '0.8.16'
evm_version = "london"
optimizer = true
optimizer_runs = 200
fs_permissions = [
    { access = "read", path = "./lib/pwn_protocol/deployments/creation/creationCode.json"},
    { access = "read", path = "./lib/pwn_protocol/deployments/external/external.json"},
    { access = "read", path = "./lib/pwn_protocol/deployments/protocol/v1.3.json"}
]

[rpc_endpoints]
# Mainnets
mainnet = "${ETHEREUM_URL}"
