[profile.default]
solc_version = '0.8.16'
evm_version = "london"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./lib/pwn_protocol/deployments/latest.json"}]

[rpc_endpoints]
# Mainnets
mainnet = "${ETHEREUM_URL}"
